ALTER TABLE tasks
  ADD COLUMN IF NOT EXISTS description TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS acceptance_criteria TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  ADD COLUMN IF NOT EXISTS parent_task_id TEXT REFERENCES tasks(id),
  ADD COLUMN IF NOT EXISTS sequence INTEGER NOT NULL DEFAULT 0;
